# URL de connexion Aiven
spring.datasource.url=jdbc:mysql://mysql-3d10909e-serviceinfo.e.aivencloud.com:15799/defaultdb?sslmode=REQUIRED

# Identifiants Aiven
spring.datasource.username=avnadmin
spring.datasource.password=MOT_DE_PASSE_SUR_RENDER

# Driver et Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true